version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
            name: "Build docker image and push to docker hub"
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                cp Dockerfile.production Dockerfile
                docker build -t thanavi/example-nodejs-circle:latest .
                docker build -t thanavi/example-nodejs-circle:${CIRCLE_SHA1} .
                docker push thanavi/example-nodejs-circle:latest
                docker push thanavi/example-nodejs-circle:${CIRCLE_SHA1}
              elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                cp Dockerfile.staging Dockerfile
                docker build -t thanavi/example-nodejs-circle-staging:latest .
                docker push thanavi/example-nodejs-circle-staging:latest
              else
                echo "This is ${CIRCLE_BRANCH}"
              fi
      - run:
          name: "Call to rancher to deploy 1"
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
            etlweather/gaucho upgrade $RANCHER_EXAMPLE_NODEJS \
              --imageUuid 'docker:thanavi/example-nodejs-circle:latest' \
              --batch_size 3 --start_first \
              --auto_complete --timeout 600 \
            /
          name: "Call to rancher to deploy 2"
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
            etlweather/gaucho upgrade $RANCHER_EXAMPLE_NODEJS \
              --imageUuid 'docker:thanavi/example-nodejs-circle:latest' \
              --batch_size 3 --start_first \
              --auto_complete --timeout 600 \
            /
          name: "Call to rancher to deploy3"
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
            etlweather/gaucho upgrade $RANCHER_EXAMPLE_NODEJS \
              --imageUuid 'docker:thanavi/example-nodejs-circle:latest' \
              --batch_size 3 --start_first \
              --auto_complete --timeout 600 \
            /
          name: "Call to rancher to deploy4"
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
            etlweather/gaucho upgrade $RANCHER_EXAMPLE_NODEJS \
              --imageUuid 'docker:thanavi/example-nodejs-circle:latest' \
              --batch_size 3 --start_first \
              --auto_complete --timeout 600 \
            /
          name: "Call to rancher to deploy5"
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
            etlweather/gaucho upgrade $RANCHER_EXAMPLE_NODEJS \
              --imageUuid 'docker:thanavi/example-nodejs-circle:latest' \
              --batch_size 3 --start_first \
              --auto_complete --timeout 600 \
            /
      - run: echo Done
